lyrics = [
{title:"Dropped Down",
lines:["dropped down got dropped down you dropped yourself down",
"stripped off feel pieces peeling off features falling to the ground",
"crossed arms to protect the surf arm-strong you're holding on",
"they're giving what donations you make",
"they're getting bigger and bigger by the prices you pay",
"to you to you look how much sweeter you taste",
"take more take all take those donations you make",
"go be who you need to be now turn around",
"I'm not there I do not stand bare naked in the freezing cold",
"my coat it's hanging over that chair will you pass it over here",
"I'm just going to stand here and watch you fall",
"I see that your potential isn't helping at all",
"potentially just doesn't make the cut",
"you're fired you're fired go set yourself on fire",
"burn down to ashes then let's go for a walk",
"then I will reteach you how to talk",
"you are like cookies I like cake and wine",
"now you repeat that you are doing just fine",
"say you're green and no one holds a lime",
"now you repeat that you are doing just fine",
"now you repeat that you are speaking in time"]},

{title:"Kidnapped in the Yukon",
lines:["dragging my snow shoes across the praries",
"I feel the weight of wet clothes on my snow shoes",
"there's dead rabbits hanging on my snow shoes",
"and lots of wet clothes lots of wet clothes",
"got the ski suit on and it's neon it's a one-piece with a pom pom on the top",
"ski googles gleaming like your teeth that are beaming I can see them through the storm",
"you're a pelican with a doormat in your mouth you're a kitten with a dartboard on your back",
"you are creasing creasing creasing until you leap",
"you're a devil in a waterbed your eyeliner is frostbite",
"you're a devil in a waterbed your eyeliner is frostbite",
"it's a so tough bull male scratches plow the road leaving gashes for the wolves to hide their wool",
"they are heaving heaving even until they bleed",
"skin that sweater new shade of purple the pitch black breathes well bag in the parcel down steeping steeping steeping until it leaks",
"you're a devil in a waterbed your eyeliner is frostbite",
"you're a devil in a waterbed your eyeliner is frostbite",
"you're changing like that"]},

{title:"Bird that Breaks",
lines:["I am a rodeo my gloves are peeling",
"I've got them trampoline I've got them teething",
"we hang from dull rope we hang from rope that breaks",
"counting our pieces they're on the recroom floor",
"we choose the roads we hoe we are the vehicles",
"I drive a stretcher I drive a stretcher",
"medicine counting medicine carve up medicine outpour medicine how come",
"I don't need a case I don't need a case I don't need a case I don't need",
"they hide the bird food they hide the bird that breaks",
"we keep our windows closed we leave the vacuum on",
"wired my jaw shut just couldn't help it",
"dagger the middle finch I've been through the skeleton",
"we choose the roads we hoe we are the vehicles",
"I drive a stretcher I drive a stretcher",
"medicine counting medicine carve up medicine outpour medicine how come",
"I don't need a case I don't need a case I don't need a case I don't need",
"a case in case you were counting no I don't need no I don't",
"a case in case you were counting no I don't need no I don't",
"no don't need no case in case a case in case"]},

{title:"They're so Sharp",
lines:["took your mask off on the second floor",
"leave your designer at the door",
"we wanna know how you take your coffee",
"pull the roof off your convertible car",
"slithering by like some sealed up statues",
"one by one like dominoes",
"he falls over then she follows",
"and I want tickets for the front row",
"they're so sharp they're so lightning they're so sharp feel them dying",
"they're so sharp feel them tightening they're so sharp",
"you dancing in a chorus line",
"move those eyes around 'till they fall like dimes",
"silver glances shifting looks held down",
"feel the pulse of those five fingers tapping hard on the chalk board",
"learn your lesson keep it in what do you think we're working for",
"they're so sharp they're so lightning they're so sharp feel them dying",
"you're the drug you're the tiger get in line",
"you dancing in a chorus line",
"move those eyes around 'till they fall like dimes",
"silver glances shifting looks held down"]},

{title:"Hot Caught", 
lines:["and it's working its so tropical", 
"gushing with no seeds",
"we don't get tired our hands stay soft",
"and you're all that I see when he's not with me",
"when you get hot caught when you get hot caught",
"when you get hot caught that's when you'll come",
"I wanna come over too I love that beach",
"and the fires they build they're so orange",
"blazing like those horses do",
"when they've got a race to lose",
"I like women I like mannequins",
"and I don't build fires for myself",
"I'm a chimney sweep cleaning up the mess",
"it's too gray ashed too gray ashed",
"it's too gray",
"when you get hot caught when you get hot caught",
"when you get hot caught that's when you'll come"]},

{title:"All of My Guardians",
lines:["drop my hands off in the fire",
"drop my arms off in the fire",
"and I don't know if you're going to go",
"I don't know if you're going to take me too",
"take me too",
"I've got grass stains on my knees",
"from the way you dragged me across the lake",
"I was just waiting for it to change",
"and I'll keep praying but I'm not going",
"werewolf you wear me out",
"I've got knots in under my skin",
"from the way you pushed hard down on the ice",
"I was just skating for it to change",
"and I'll keep praying but i'm not going",
"and I'll rip it off I'll take your tag",
"you summon on like I never had",
"and I don't know if you're going to take me too",
"I don't know if you're going to take me too",
"take me too",
"werewolf you wear me out",
"I've rubber tires as my teeth",
"the others fallen down from where you kicked me",
"my mouth drives trucks now if you didn't know",
"and yes they're charging",
"all of my guardians all my groves"]},

{title:"The All Best",
lines:["two can make it up it's the last time to",
"be destructive it's the all best",
"into the hush hush tights",
"it's the best goal to stick to",
"it's a temptress ever after",
"good luck you'll need some",
"very good luck",
"into mind it starts that we caught after",
"it's the anxious way to be had",
"into the hush hush tights",
"it's the best goal to stick to",
"it's a temptress ever after",
"good luck you'll need a sistine"]},


{title:"Georgia",
lines:["babies I hate to be the one who knows",
"that dr. president wants to take your fingers for dollars",
"this little piggy goes to the diamond market",
"this little piggy goes to the butcher shop",
"this little pig goes to a pair of sneakers",
"made by a baby just like you",
"yeah your momma's probably going to cry",
"and your daddy will protect you well he'll try",
"but how can you hide from the dragons of destruction?",
"how little kids they just don't realize",
"the price of their extinction",
"can help to drive all the cars",
"on the freeways of the world",
"they'll trade a baby for a lap dance",
"they'll trade a baby for a double latte",
"they'll trade a baby for a new car",
"a baby for a facelift for your wife",
"it's not a hold on to your hat kids",
"it's a hold on to your homes",
"because the moths have arrived",
"they want to eat through your clothes",
"surrounding your schools because",
"they want you to learn",
"their dinner party's tonight",
"all eyes on the caviar ‘cause they like little eggs",
"the younger the feed the better it gets",
"because the youngest feed is the future of the enemies",
"they'll trade a finger for a fur coat",
"they'll trade a finger for a cut and blow dry",
"they'll trade a finger for a silk scarf",
"a finger for a hamburger with fries",
"one day you should ask yourself a question",
"would you give up your hand for a handful of lives?",
"would you give up your tongue for a mouthful of voices?",
"would you give a glass of blood to help someone survive?",
"or do you give yourself over to a country a country of",
"hot country"]},

{title:"Ice Life",
lines:["out of the oven comes the cookies",
"perfectly uniformed tucked and bowing",
"to the labels to the suits",
"to the television hands and knees screaming",
"‘cause I am the snowman I'm the abominable snowman",
"my tummy's big and white so I can plow you over and over",
"my arms are sticks my hands are mitts ‘cause I'm the abominable snowman",
"watch your fires watch your pits ‘cause I will freeze you like hell freezing over",
"lying in the sunbed makeup",
"melting off like globs off icing",
"is anyone watching?",
"‘cause I'm so hungry I lick me fingers",
"I lick my fingers my fingers of icing",
"take your SAT's take your ACT's",
"let ‘em standardize standardize test you",
"here's a vogue magazine go upstairs and study",
"the test date is tomorrow",
"hawk can hawk can bend hawk can see",
"I cannot straighten my esses",
"distants say they say it's asking season",
"I'll take my plate over there",
"for all I can see I'd rather take it raw",
"don't give a rat's head if it's alright it's awry",
"have you done your reps? have you changed your hair?",
"have you changed your mind? there's nail polish everywhere",
"‘cause I am the snowman I'm the abominable snowman",
"my tummy's big and white so I can plow you over and over",
"my arms are sticks my hands are mitts ‘cause I'm the abominable snowman",
"watch your fires watch your pits ‘cause I will freeze you like hell freezing over",
"all the good things that don't come back to us",
"it don't know how to be the expert all claw"]},

{title:"It's a Fortress",
lines:["take me out for a treat because I'm useless with rings",
"long gloved accessory- just a cover for stitches",
"but it's a fortress the one they talk about",
"and the ribbons are long so you can tie them down",
"it's the necktie that they scream about",
"you cannot crow like the others ‘cause they're calling you and you saw",
"you cannot crow for the like for the like",
"undress me don't take it off",
"I've got thorns there under my stockings",
"stockings roll them down",
"I've got a secret bend down",
"but it's a fortress the one they talk about",
"and the ribbons are long so you can tie them down",
"it's the necktie that they scream about",
"you cannot crow like the others ‘cause they're calling you and you saw",
"you cannot crow for the like for the like",
"go sore go sorer"]},


{title:"Moisturizer (Wheat Calls)",
lines:["going to the guesthouse gonna write it all down",
"lie on the kitchen floor and sharpen the knives",
"the sun's out today like it was yesterday can't even keep my eyes half open",
"someone turned out the lights someone turned out the lights",
"my face is itchy all the time",
"the hostess is thirsty from breaking the stories",
"her mouth's full of salt and she can't find the water",
"put up your hair put up your hands drink a bottle of hand sanitizer",
"it won't let you down it won't let you down",
"my face is itchy",
"all the time my face is itchy",
"all the time",
"you've got to moisturize her caulk up the lines",
"don't let anyone know how long you've been here",
"moisturizer caulk up the lines",
"don't let anyone know how long it's been",
"wheat wheat"]},

{title:"One Lark",
lines:["one lark or another you're going to find",
"one lark or another",
"going to cut it together it will be fine",
"going to cut it together",
"going to keep it in my locket for the cost of the storage",
"going to keep it in my locket",
"one lark or",
"one lark or",
"I got harder and you got deeper in my spine the sword is sticking out",
"inseam it's in the inseam and though I've cut you please do not cut me",
"keep digging for diamonds for all those hands",
"keep digging for diamonds",
"they get all righteous we won't defend they get all righteous",
"going to keep it in my locket for the cost of the storage",
"one lark or",
"one lark or",
"I got harder and you got deeper in my spine the sword is sticking out",
"inseam it's in the inseam and though I've cut you",
"please do not cut me",
"getting all ripe 'cause it's the wildest way it seems to be cashed out cashed out",
"dust like cashed out and softening",
"won't stay soft for the weakest"]},

{title:"Tight Score",
lines:["hey can you tell me how she's doing",
"hey can you tell me",
"how she's doing",
"you know you know",
"white daughter's got the tight score",
"hey doesn't she wanna know I haven't been to work in seven days",
"hey doesn't she care the bathmat's filling up",
"you know you know",
"white daughter's got the tight score",
"a rolling stone gathers its clothes and pushes out the door",
"don't bother changing the locks",
"a rolling stone gathers up speed once it kicks itself free",
"don't think it's all your fault",
"you can operate on me",
"all the things they say alone",
"you can operate on me",
"you can't wait to cut me up",
"all the things that are alone",
"you can't wait to cut me up",
"I know she put you through the most hair-raising times",
"but you came out fine yeah you came out fine",
"hey can you tell me where she's gone",
"hey can you tell me where she's gone",
"you know you know",
"white daughter's got the tight score",
"you can operate on me",
"all the things they say alone",
"you can operate on me",
"you can't wait to cut me up",
"all the things that are alone",
"you can't wait to cut me up",
"I know she put you through the most hair-raising times",
"but you came out fine"]},

{title:"Coast That's Closest",
lines:["steal those days in nets",
"swept up with violence",
"cage caught up and locked",
"flat crow pressed in the pages",
"he's the hardest hardest ghost I know",
"he's white like a phantom",
"wasn't through when the sand ran out",
"like to work my fingers to the bone",
"treadmill me till the white pokes out",
"pick the coast that's closest",
"all the scattered",
"times when",
"up like dried ice",
"all the islands ended",
"pick the closest",
"rummage through the leaves",
"you'll find fire in the pile",
"and lift the veil for all to see",
"you'll find coat hanger heartache",
"he's the hardest hardest ghost I know",
"he's white like a phantom",
"wasn't through when the sand ran out",
"like to work my fingers to the bone",
"treadmill me till the white pokes out",
"pick the coast that's closest",
"pick the coast that's closest"]},

{title:"We Were Figs",
lines:["you sense I'm half there and you're right",
"it dreams like hot times",
"are we miraging? are we oasis?",
"q q the desert",
"tell the task to do it uncut sawed up",
"that severed skull is not the only one",
"to be honest there's no dead half to compete with",
"all one",
"palm springs is harmony",
"and it's so right",
"count the sand castle",
"cracked nails and score",
"cracked nails and scorpion",
"you are the hole in one",
"tell the task to do it uncut sawed up",
"that severed skull is not the only one",
"to be honest there's no dead half to compete with",
"all one",
"the hard grows into another one to another one",
"cannot finish no we're not the hidden land",
"turn on the other one into another one",
"it's another one we're not the hidden land"]},

{title:"In Manilla",
lines:["If I didn't get injuries I could still fight",
"but the cuts have slowed me down have made the floors stick", 
"got five ways to catch a cold had plenty of times to knock me out",
"Bet you didn't mean it bet you've got three times more than me",
"'cause time is racing time is erasing I bet you'd go half way up my hand",
"you're an oil blot you never come out kept the fruits still all night they like to go bad"]},

{title:"Ruen Pair",
lines:["Caught up on the fences of the dove tongue-tied it's not my way to give but this one's known me since the day I started",
"You've got it figured out you've gotta con the guards just to guard it",
"you got the saint's damage you know we'll all be safe again",
"It's writhing it's waiting for nothing alone it's a forever it's hidden it can't come back it's sordid it's got great alliance it never is honest it never comes back come back",
"I could sell the graves I could start and start again I've got the current air but I could salt it so it lasts", 
"You've got it figured out you've gotta con the guards just to guard it",
"you got the saint's damage you know we'll all be safe again",
"It's writhing it's waiting for nothing alone it's a forever it's hidden it can't come back it's sordid it's got great alliance it never is honest it never comes back come back"]},

{title:"Modified My Knife",
lines:["When you come crying you make your claim make your gains make your cane",
"creaking in my pocket creaking in your pocket creep in my back pocket", 
"freeze grays to graze outside all sane all groves all grave riding! sailing! waiting", 
"waiting for my little boots little boots to save my life",
"back hand leader modified modified my knife"]},

{title:"For the Bond",
lines:["Trash days we’re trash times for a trash day trash days we’re trash times go out again",
"waited for those hot times to call",
"gonna beat up gonna beat up those hot times",
"go to sleep it’s true wake up it’s true it’s all night it’s all night",
"never tried your hand at dry never tried your hand at grace",
"never tried your hand at blame never tried your hand at outside",
"never tried your hand at dye never tried your hand at books",
"never tried your hand at air never tried your hand at tried",
"take some of my things because I’ve got enough wear this I got this for you",
"take some of my things because I’ve got enough wear this I got this stuff for you",
"I mean I mean don’t come along",
"that’s what I, I mean I mean don’t come along at all",
"I mean I mean don’t come along I mean don’t come",
"never tried your hand at dry never tried your hand at grace",
"never tried your hand at blame never tried your hand at outside",
"never tried your hand at dye never tried your hand at books",
"never tried your hand at air never tried your hand at tried",
"that’s all it takes to take those husbands back that’s all it takes to take those husbands back"]}
];
